//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_5_and_6.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Module_5_and_6", ConfigurationName="ServiceReference2.Program_2Soap")]
    public interface Program_2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="Module_5_and_6/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="Module_5_and_6/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Module_5_and_6/SelectData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SelectData();
        
        [System.ServiceModel.OperationContractAttribute(Action="Module_5_and_6/SelectData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Module_5_and_6/insertData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int insertData(string name, string classname);
        
        [System.ServiceModel.OperationContractAttribute(Action="Module_5_and_6/insertData", ReplyAction="*")]
        System.Threading.Tasks.Task<int> insertDataAsync(string name, string classname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Program_2SoapChannel : Module_5_and_6.ServiceReference2.Program_2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Program_2SoapClient : System.ServiceModel.ClientBase<Module_5_and_6.ServiceReference2.Program_2Soap>, Module_5_and_6.ServiceReference2.Program_2Soap {
        
        public Program_2SoapClient() {
        }
        
        public Program_2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Program_2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Program_2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Program_2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet SelectData() {
            return base.Channel.SelectData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectDataAsync() {
            return base.Channel.SelectDataAsync();
        }
        
        public int insertData(string name, string classname) {
            return base.Channel.insertData(name, classname);
        }
        
        public System.Threading.Tasks.Task<int> insertDataAsync(string name, string classname) {
            return base.Channel.insertDataAsync(name, classname);
        }
    }
}
