//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_inside_WCF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProgram_4")]
    public interface IProgram_4 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram_4/selectdata", ReplyAction="http://tempuri.org/IProgram_4/selectdataResponse")]
        System.Data.DataSet selectdata();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram_4/selectdata", ReplyAction="http://tempuri.org/IProgram_4/selectdataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> selectdataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram_4/insertData", ReplyAction="http://tempuri.org/IProgram_4/insertDataResponse")]
        int insertData(string name, string classname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram_4/insertData", ReplyAction="http://tempuri.org/IProgram_4/insertDataResponse")]
        System.Threading.Tasks.Task<int> insertDataAsync(string name, string classname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProgram_4Channel : ASP_inside_WCF.ServiceReference1.IProgram_4, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Program_4Client : System.ServiceModel.ClientBase<ASP_inside_WCF.ServiceReference1.IProgram_4>, ASP_inside_WCF.ServiceReference1.IProgram_4 {
        
        public Program_4Client() {
        }
        
        public Program_4Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Program_4Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Program_4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Program_4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet selectdata() {
            return base.Channel.selectdata();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> selectdataAsync() {
            return base.Channel.selectdataAsync();
        }
        
        public int insertData(string name, string classname) {
            return base.Channel.insertData(name, classname);
        }
        
        public System.Threading.Tasks.Task<int> insertDataAsync(string name, string classname) {
            return base.Channel.insertDataAsync(name, classname);
        }
    }
}
